{% set name = "pytest-sugar" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f1e74c1abfa55f7241cf7088032b6e378566f16b938f3f08905e2cf4494edd46

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  #[py<38]

requirements:
  host:
    - python
    - pip
    - poetry-core
    - setuptools >=40.6.0
    - wheel
  run:
    - python
    - packaging >=21.3
    - pytest >=6.2.0
    - termcolor >=2.1.0

test:
  imports:
    - pytest_sugar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Teemu/pytest-sugar
  dev_url: https://github.com/Teemu/pytest-sugar/
  doc_url: https://github.com/Teemu/pytest-sugar/tree/main#readme
  summary: Pytest plugin that adds a progress bar and other visual enhancements
  description: |
    pytest-sugar is a plugin for pytest that changes the default look and feel of pytest
    (e.g. progressbar, show tests that fail instantly).
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - ocefpaf