{% set name = "pytest-sugar" %}
{% set version = "0.9.3" %}
{% set sha256 = "1630b5b7ea3624919b73fde37cffb87965c5087a4afab8a43074ff44e0d810c4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - termcolor >=1.1.0
    - py
    - pytest >=2.9
    - packaging >=14.1

test:
  imports:
    - pytest_sugar

about:
  home: https://github.com/Frozenball/pytest-sugar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'a plugin for py.test that changes the default look and feel of py.test '
  description: |
    pytest-sugar is a plugin for py.test that shows failures and errors instantly and 
    shows a progress bar.  
  doc_url: http://pydoc.net/pytest-sugar/0.8.0/
  dev_url: https://github.com/Frozenball/pytest-sugar

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
