{% set name = "pytest-sugar" %}
{% set version = "0.9.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c4793495f3c32e114f0f5416290946c316eb96ad5a3684dcdadda9267e59b2b8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - packaging >=14.1
    - pytest >=2.9
    - termcolor >=1.1.0

test:
  imports:
    - pytest_sugar
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pivotfinland.com/pytest-sugar/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'a plugin for py.test that changes the default look and feel of py.test '
  description: |
    pytest-sugar is a plugin for py.test that shows failures and errors instantly and
    shows a progress bar.
  dev_url: https://github.com/Teemu/pytest-sugar/

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - ocefpaf
