{% set name = "pytest-sugar" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6422e83258f5b0c04ce7c632176c7732cab5fdb909cb39cca5c9139f81276c0a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  #[py<38]

requirements:
  host:
    - python
    - pip
    - setuptools >=40.6.0
    - wheel
    - poetry-core
  run:
    - python
    - packaging >=21.3
    - pytest >=6.2.0
    - termcolor >=2.1.0

test:
  imports:
    - pytest_sugar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Teemu/pytest-sugar
  dev_url: https://github.com/Teemu/pytest-sugar/
  doc_url: https://github.com/Teemu/pytest-sugar/tree/main#readme
  summary: Pytest plugin that adds a progress bar and other visual enhancements
  description: |
    pytest-sugar is a plugin for pytest that changes the default look and feel of pytest
    (e.g. progressbar, show tests that fail instantly).
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - ocefpaf