travis:
  secure:
    BINSTAR_TOKEN: GpmHtxh8GiTcbIjGkmkpOEFKqkY95Nw5d7a9g/QYusfYIRHsiDlp3+U7Q5jmimI/lO+Zwl+3XD9L/rY1TytmdG2lrmOF35gvsU3UVXeZhyioGstRpehiybAv3osiv2pmkJSAo8Bemkfvuck3PgWt9hpT5WZj402/5C2iEwDD2MCcp2tyxrYM1dSEJterXNo6T/qcbjxxxknsn3qzHzLU+UJRoTOwT4CJimdWOxvukHn78FGYv+wayKTyrNwyaq2XWBTp7tZNxiAma/bMxFiKXUyPVJXNKcPEA5cOP+GeJg01ypKIANkn0sYEZeUIbdSA9OrJMBd6gMWlTlM8Q2X0iXSHew7eD47PDvJ+CORxgLvQjOcEqKZ+5pCMv3elzvbnTOwjA0pmSHxIkDZX1RH7jtdEaMks5wom4EaiHBP/NNsHJKn5kPm5ULuElE70JZJOGd7IyXl9BkpIE4b30XgeeShzsPQac0MipTIXgpBiQG3dChbu4rgNZgPzwzL0QPBC/jHOJDkjpu5nCPPC8Om6l5bJSH2D6s+XgsLxXmot3W/OA19E+a6LOSdtnFXQArJFTqp1bsrgmkUlpzGs/eNGHaTBbCOu2i7b9MDoboAqTOQZcPmvN0SgRmN1RN9NYKVKWk+/fOggFkIg+dXhbVTnF+I+YDG/xKysRmnUm5r5ebE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
