travis:
  secure:
    BINSTAR_TOKEN: ZtDSwWOcGLY8dCNw9bhy5iUq0XWVNkFgwGQ0/7ym4a/Z7UuNlB5aMsZw/e3gqT4naqW8BgNO1l1GD9+6pF3c+CpKuLfOCeZRzZLA5IqLVzlLNRjYBOnjuRCS8aG84zEudz1N4AL7mo1gHsU6Q+CMPhuVruFecXYSogyjH/Rq8O4/AW80On3jtD+nGECESmttwBAcrNab1uH2pY+YcPSody6fw3Ouo5DID3h6V+bSLJUM/uVGm17Pb0ym8wnzi+wT1i6oj3aUtHt5tKT0+6xqNqmtqKaoLVT1TVjYTVd3bTEiuGkBD4nWxAxgSSOGuCXsf3aWENxNI/KzegVitnBoNWkFkyJxlI6h8r6QBaeeqnIchraABtTytwtKN64aIQwKPtH42VhFXl8Io4wKQGzj9pzTuX2snctoPfWpUlTpa5IWPo+m54Dq1idp6BOsUC7HtBazgtpZcDFDWfavU0H6H1pUhnZJTLHU8UWfYhUoo8ujcfC8zQUKMlbSnjxZipSEvOhuJOo3v5x6MMqaTDmnuNByo43fY2Ehoa5xRZR1x+tYTvv5OnO5cEuukcv/BCd2LzuX0ecrGFFRct5CxEsaxZ/ZGzcdcVmDqeGqLOBygx0rGx2/sblYk3jNHAl9H0F7bUUHp3a3KM/hZknCU6jmoqSJaZBFq4PXV0r+AOT/1cQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
